defaults: &defaults
  api:
    port: 3000

  mongo:
    url: "mongodb+srv://fakemailforregister:FEdvdL4Leml4Wpin@madiatracker.sabzsmo.mongodb.net/?retryWrites=true&w=majority"

  logger:
    name: Media Tracker Api
    level: debug
    levels:
      trace:
      debug: STDOUT
      info:
      warn:
      error: STDERR
      fatal:

  fillSettings:
    games:
      cron: '0 */1 * * * *'
      limitItemsForPage: 25
      isJobStart: false
    books:
      cron: '0 */1 * * * *'
      limitItemsForPage: 40
      isJobStart: false

development:
  <<: *defaults

production:
  <<: *defaults

  logger:
    name: media-tracker
    level: debug
    levels:
      trace: STDOUT
      debug: STDOUT
      info: STDOUT
      warn: STDOUT
      error: STDERR
      fatal: STDERR
