defaults: &defaults
  api:
    port: 3000

  mongo:
    url: "mongodb+srv://fakemailforregister:FEdvdL4Leml4Wpin@madiatracker.sabzsmo.mongodb.net/?retryWrites=true&w=majority"

  logger:
    name: Media Tracker Api
    level: debug
    levels:
      trace:
      debug: STDOUT
      info:
      warn:
      error: STDERR
      fatal:

development:
  <<: *defaults

production:
  <<: *defaults

  logger:
    level: debug
    levels:
      trace:
      debug: STDOUT
      info: ./log/info.log
      warn: ./log/warn.log
      error: ./log/error.log
      fatal: ./log/fatal.log
